version: '3.4'

services:
    chatchat:
        image: chatchat
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
          - NODE_ENV=production
          - DATABASE_URL=postgresql://username:password@database/appdb?sslmode=disable
          - NEXTAUTH_URL=http://localhost:3000
          - NEXTAUTH_SECRET=supersecrettoken
          - EMAIL_HOST=smtp.example.com
          - EMAIL_PORT=465
          - EMAIL_USERNAME=user@example.com
          - EMAIL_PASSWORD=super_secret_smtp_password
          - EMAIL_USE_SSL=true
          - EMAIL_FORM=FirstName LastName <user@example.com>
          #- GITHUB_CLIENT_ID=
          #- GITHUB_CLIENT_SECRET=
          #- GOOGLE_CLIENT_ID=
          #- GOOGLE_CLIENT_SECRET=
        ports:
            - 3000:3000
